# -*- coding: utf-8 -*-
"""T-Shirt Trove.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQ9bQnT0uxelZjMlXJQxC6vIM6yylZiC
"""

from scipy.optimize import minimize
import numpy as np

# Define objective function (negative for minimization)
def objective(x):
    p, a = x
    return -(p * (100 - p + np.sqrt(max(0, a))) - a)

# Initial guess
x0 = [50, 500]  # Starting point: price = $50, advertising = $500

# Define bounds
bounds = ((50, None), (0, 1000))  # price >= 50, 0 <= advertising <= 1000

# Optimize
result = minimize(objective, x0, bounds=bounds, method='SLSQP')

# Print results
print(f"Optimal T-shirt Price: ${result.x[0]:.2f}")
print(f"Optimal Advertising Dollars: ${result.x[1]:.2f}")
print(f"Maximum Profit: ${-result.fun:.2f}")

